apiVersion: apps/v1
kind: Deployment
metadata:
  name: plausible
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plausible
  template:
    metadata:
      labels:
        app: plausible
    spec:
      initContainers:
      - command:
        - bash
        - -c
        - /entrypoint.sh db createdb && /entrypoint.sh db migrate && /entrypoint.sh db init-admin
        env:
        - name: ADMIN_USER_EMAIL
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_EMAIL
              name: plausible
        - name: ADMIN_USER_NAME
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_NAME
              name: plausible
        - name: ADMIN_USER_PWD
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_PWD
              name: plausible
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: plausible
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: plausible
        - name: CLICKHOUSE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: CLICKHOUSE_DATABASE_URL
              name: plausible
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              key: BASE_URL
              name: plausible
        image: plausible/analytics:dev
        imagePullPolicy: Always
        name: plausible-init
      containers:
      - command:
          - /bin/bash
          - -c
          - /entrypoint.sh run
        env:
        - name: ADMIN_USER_EMAIL
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_EMAIL
              name: plausible
        - name: ADMIN_USER_NAME
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_NAME
              name: plausible
        - name: ADMIN_USER_PWD
          valueFrom:
            secretKeyRef:
              key: ADMIN_USER_PWD
              name: plausible
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: DATABASE_URL
              name: plausible
        - name: SECRET_KEY_BASE
          valueFrom:
            secretKeyRef:
              key: SECRET_KEY_BASE
              name: plausible
        - name: CLICKHOUSE_DATABASE_URL
          valueFrom:
            secretKeyRef:
              key: CLICKHOUSE_DATABASE_URL
              name: plausible
        - name: BASE_URL
          valueFrom:
            configMapKeyRef:
              key: BASE_URL
              name: plausible
        image: plausible/analytics:dev
        imagePullPolicy: Always
        name: plausible
        ports:
        - name: http
          containerPort: 8000
        resources: {}
      restartPolicy: Always
