apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: plausible-db
spec:
  enableConnectionPooler: true
  connectionPooler:
    mode: session
    resources:
      requests:
        cpu: 250m
        memory: 100Mi
      limits:
        cpu: "1"
        memory: 100Mi
  teamId: "plausible"
  volume:
    size: 1Gi
  numberOfInstances: 1
  users:
    plausible:  # database owner
    - superuser
    - createdb
  databases:
    plausible: plausible  # dbname: owner
  postgresql:
    version: "12"
  resources:
    requests:
      cpu: "100m"
      memory: "1024Mi"
    limits:
      cpu: "1"
      memory: "1024Mi"
